/*
  Lista de presentes — Júlia & Wesley
  ------------------------------------
  Cada item tem um campo "link". Preencha com a URL real do anúncio no
  Mercado Livre (a mesma que está na sua lista de favoritos). A ordem
  abaixo é a mesma ordem em que os itens apareceram nos prints da lista,
  então é só ir copiando um a um de cima para baixo.

  categoria (tag mostrada no card):
    cozinha | utensilios | sala | lavanderia | quarto | banheiro

  unique:
    true  -> presente "grande", só pode ser dado por UMA pessoa (some da lista
             / fica marcado como "já escolhido" pra sempre que alguém confirmar)
    false -> presente que pode ser dado por mais de uma pessoa (ex: roupa de
             cama, toalhas) — não trava, não precisa de confirmação

  destaque: true -> aparece na aba "Presentes Especiais" no topo da página
*/

const PRESENTES = [
  { id: "cooktop-gas", nome: "Cooktop a Gás Fischer 5 Bocas Fit Line Trempe Iron", preco: 614.18, categoria: "cozinha", unique: true, destaque: true, img: "cooktop-gas.webp", link: "https://www.mercadolivre.com.br/cooktop-a-gas-fischer-5-bocas-fit-line-trempe-iron/p/MLB42739903?pdp_filters=item_id%3AMLB4592568069&sid=bookmarks#polycard_client=wishlist&wid=MLB4592568069&sid=bookmarks" },
  { id: "purificador-agua", nome: "Purificador de Água Consul Eletrônico com Refrigeração", preco: 506.00, categoria: "cozinha", unique: true, destaque: true, img: "purificador-agua.webp", link:"https://www.mercadolivre.com.br/purificador-filtro-de-agua-consul-eletronico-com-refrigeracao-cpb33ab-branco/p/MLB20199064?pdp_filters=item_id%3AMLB3249349828&sid=bookmarks#polycard_client=wishlist&wid=MLB3249349828&sid=bookmarks" },
  { id: "microondas", nome: "Microondas Panasonic 21L Branco Espelhado", preco: 494.21, categoria: "cozinha", unique: true, destaque: true, img: "microondas.webp", link: "https://www.mercadolivre.com.br/microondas-panasonic-nn-st27lwru-21l-branco-espelhado-tecnologia-pega-facil/p/MLB16591406?pdp_filters=item_id%3AMLB1885277026&sid=bookmarks#polycard_client=wishlist&wid=MLB1885277026&sid=bookmarks" },
  { id: "fritadeira-eletrica", nome: "Fritadeira Elétrica Wap Air Fryer Oven Digital 12 Litros", preco: 499.00, categoria: "cozinha", unique: true, destaque: true, img: "fritadeira-eletrica.webp", link: "https://www.mercadolivre.com.br/fritadeira-eletrica-wap-air-fryer-oven-digital-black-inox-12-litros-com-revestimento-antiaderente/p/MLB42225245?pdp_filters=item_id%3AMLB5904720592&sid=bookmarks#polycard_client=wishlist&wid=MLB5904720592&sid=bookmarks" },
  { id: "rack-tv-75", nome: "Rack para TV até 75\" Multimóveis Retrô 3 Portas", preco: 524.35, categoria: "sala", unique: true, destaque: true, img: "rack-tv-75.jpg", link: "https://www.mercadolivre.com.br/rack-para-tv-ate-75-polegadas-180cm-3-portas-retro-multimoveis-mp1102-pretomadeirado/p/MLB62203365?pdp_filters=item_id%3AMLB6285949308&sid=bookmarks#polycard_client=wishlist&wid=MLB6285949308&sid=bookmarks" },
  { id: "smart-tv-samsung", nome: "Smart TV Samsung Crystal 55\" 4K", preco: 2699.00, categoria: "sala", unique: true, destaque: true, img: "smart-tv-samsung.jpg", link: "https://www.mercadolivre.com.br/smart-tv-un55u8100fgxzd-crystal-55-4k-preto-samsung-bivolt/p/MLB50308413?sid=bookmarks#polycard_client=wishlist&wid=MLB4110379897&sid=bookmarks" },
  { id: "geladeira-electrolux", nome: "Geladeira Electrolux Frost Free 400L Inverter Inox", preco: 2999.00, categoria: "cozinha", unique: true, destaque: true, img: "geladeira-electrolux.webp", link: "https://www.mercadolivre.com.br/geladeira-electrolux-frost-free-400l-inverter-inox-if44s/p/MLB65451315?pdp_filters=item_id%3AMLB6402686004&sid=bookmarks#polycard_client=wishlist&wid=MLB6402686004&sid=bookmarks" },
  { id: "maquina-lavar", nome: "Máquina de Lavar Electrolux 14,5kg Efficient Branca", preco: 1939.00, categoria: "lavanderia", unique: true, destaque: true, img: "maquina-lavar.webp", link: "https://www.mercadolivre.com.br/maquina-de-lavar-electrolux-145kg-efficient-branca-com-cesto-inox-e-jetclean-lee15/p/MLB51399050?pdp_filters=item_id%3AMLB5697803830&sid=bookmarks#polycard_client=wishlist&wid=MLB5697803830&sid=bookmarks" },
  { id: "lavadora-semiautomatica", nome: "Lavadora Semiautomática Colormaq 10kg Branca", preco: 488.01, categoria: "lavanderia", unique: true, destaque: true, img: "lavadora-semiautomatica.webp", link: "https://www.mercadolivre.com.br/lavadora-semiautomatica-lcs-10kg-branca-colormaq-110v-branco/p/MLB14815387?pdp_filters=item_id%3AMLB5899143262&sid=bookmarks#polycard_client=wishlist&wid=MLB5899143262&sid=bookmarks" },
  { id: "robo-aspirador", nome: "Robô Aspirador Kabum Smart 900 com Base e Wi-Fi", preco: 1529.00, categoria: "lavanderia", unique: true, destaque: true, img: "robo-aspirador.webp", link: "https://www.mercadolivre.com.br/robo-aspirador-kabum-smart-900-passa-pano-com-base-alexa-wi-fi/p/MLB42443995?pdp_filters=item_id%3AMLB6895942928&sid=bookmarks#polycard_client=wishlist&wid=MLB6895942928&sid=bookmarks" },

  { id: "rack-tv-65", nome: "Rack para TV até 65\" Turim 2 Portas 1 Prateleira", preco: 504.94, categoria: "sala", unique: true, destaque: false, img: "rack-tv-65.webp", link: "https://www.mercadolivre.com.br/rack-para-tv-ate-65-polegadas-turim-2-portas-1-prateleira-cor-titaniumnaturale/p/MLB24034109?pdp_filters=item_id%3AMLB3947167363&sid=bookmarks#polycard_client=wishlist&wid=MLB3947167363&sid=bookmarks" },
  { id: "forno-eletrico", nome: "Forno Elétrico de Bancada Nardelli Top60 60L Black", preco: 439.80, categoria: "cozinha", unique: true, destaque: false, img: "forno-eletrico.webp", link: "https://www.mercadolivre.com.br/forno-eletrico-de-bancada-110v-nardelli-top60-60litros-black/p/MLB18640232?pdp_filters=item_id%3AMLB2732475035&sid=bookmarks#polycard_client=wishlist&wid=MLB2732475035&sid=bookmarks" },
  { id: "espremedor-frutas", nome: "Espremedor de Frutas Arno Suco Express 0,75L", preco: 89.99, categoria: "cozinha", unique: true, destaque: false, img: "espremedor-frutas.webp", link: "https://www.mercadolivre.com.br/espremedor-de-frutas-suco-express-075l-preto-cp31-110/p/MLB19712798?pdp_filters=item_id%3AMLB3951754725&sid=bookmarks#polycard_client=wishlist&wid=MLB3951754725&sid=bookmarks" },
  { id: "liquidificador", nome: "Liquidificador Turbo Mondial 1100W", preco: 149.00, categoria: "cozinha", unique: true, destaque: false, img: "liquidificador.webp", link: "https://www.mercadolivre.com.br/liquidificador-turbo-mondial-1100w-l-1100-bi/p/MLB17006479?pdp_filters=item_id%3AMLB5904552748&sid=bookmarks#polycard_client=wishlist&wid=MLB5904552748&sid=bookmarks" },
  { id: "panela-pressao-eletrica", nome: "Panela de Pressão Elétrica Digital 5L Mondial 900W", preco: 369.00, categoria: "cozinha", unique: true, destaque: false, img: "panela-pressao-eletrica.webp", link: "https://www.mercadolivre.com.br/panela-de-pressao-eletrica-digital-5l-mondial-900w-pe-38/p/MLB21829040?pdp_filters=item_id%3AMLB5446464418&sid=bookmarks#polycard_client=wishlist&wid=MLB5446464418&sid=bookmarks" },
  { id: "chaleira-eletrica", nome: "Chaleira Elétrica 1,8L 1200W Atacama Nohara", preco: 37.90, categoria: "cozinha", unique: true, destaque: false, img: "chaleira-eletrica.webp", link: "https://www.mercadolivre.com.br/chaleira-eletrica-18l-1200w-atacama-nohara/p/MLB13409957?pdp_filters=item_id%3AMLB7258833950&sid=bookmarks#polycard_client=wishlist&wid=MLB7258833950&sid=bookmarks" },
  { id: "ferro-de-passar", nome: "Ferro de Passar a Vapor Electrolux Efficient 1200W", preco: 89.90, categoria: "lavanderia", unique: true, destaque: false, img: "ferro-de-passar.webp", link: "https://www.mercadolivre.com.br/ferro-de-passar-secovapor-electrolux-efficient-base-antiaderente-vapor-vertical-extra-1200w-esi11/p/MLB19867726?pdp_filters=item_id%3AMLB5759998666&sid=bookmarks#polycard_client=wishlist&wid=MLB5759998666&sid=bookmarks" },
  { id: "jogo-talheres", nome: "Jogo de Talheres Cabo Madeira 36 Peças Aço Inox", preco: 94.80, categoria: "utensilios", unique: true, destaque: false, img: "jogo-talheres.webp", link: "https://www.mercadolivre.com.br/jogo-de-talheres-cabo-madeira-36-pecas-aco-inox/up/MLBU3287643846?pdp_filters=item_id%3AMLB4120957621&sid=bookmarks#polycard_client=wishlist&wid=MLB4120957621&sid=bookmarks" },
  { id: "grill-sanduicheira", nome: "Grill Sanduicheira Cadence Elétrica Chapa Mista", preco: 93.41, categoria: "cozinha", unique: true, destaque: false, img: "grill-sanduicheira.webp", link: "https://www.mercadolivre.com.br/grill-sanduicheira-cadence-san400-eletrica-chapa-misteira-tostex-tostequeira-hamburguer-click-preto-127v/up/MLBU2296024218?pdp_filters=item_id%3AMLB3605050985&sid=bookmarks#polycard_client=wishlist&wid=MLB3605050985&sid=bookmarks" },
  { id: "batedeira-planetaria", nome: "Batedeira Planetária Mondial 700W", preco: 279.00, categoria: "cozinha", unique: true, destaque: false, img: "batedeira-planetaria.webp", link: "https://www.mercadolivre.com.br/batedeira-planetaria-mondial-700w-bp-03-b/p/MLB18623993?pdp_filters=item_id%3AMLB2723739722&sid=bookmarks#polycard_client=wishlist&wid=MLB2723739722&sid=bookmarks" },
  { id: "batedeira-pratica", nome: "Batedeira Prática Mondial 400W", preco: 78.89, categoria: "cozinha", unique: true, destaque: false, img: "batedeira-pratica.webp", link: "https://www.mercadolivre.com.br/batedeira-pratica-mondial-400w-b-44-b/p/MLB16016316?pdp_filters=item_id%3AMLB3602385150&sid=bookmarks#polycard_client=wishlist&wid=MLB3602385150&sid=bookmarks" },
  { id: "aparelho-jantar", nome: "Aparelho de Jantar e Chá Ryo Maresia 20 Peças", preco: 277.80, categoria: "utensilios", unique: true, destaque: false, img: "aparelho-jantar.webp", link: "https://www.mercadolivre.com.br/aparelho-de-jantar-e-cha-ryo-maresia-20-pecas-branco-e-marrom-oxford/p/MLB33630217?pdp_filters=item_id%3AMLB3611214641&sid=bookmarks#polycard_client=wishlist&wid=MLB3611214641&sid=bookmarks" },
  { id: "jogo-xicara", nome: "Jogo de Xícara para Café Napoli 12 Peças", preco: 34.40, categoria: "utensilios", unique: true, destaque: false, img: "jogo-xicara.webp", link: "https://www.mercadolivre.com.br/jogo-xicara-80ml-cafe-pires-vidro-napoli-12-peca-em-casa-tem-incolor-liso/p/MLB64536928?pdp_filters=item_id%3AMLB4746289567&sid=bookmarks#polycard_client=wishlist&wid=MLB4746289567&sid=bookmarks" },
  { id: "panela-arroz", nome: "Panela Elétrica de Arroz Mondial 700W", preco: 192.90, categoria: "cozinha", unique: true, destaque: false, img: "panela-arroz.webp", link: "https://www.mercadolivre.com.br/panela-eletrica-de-arroz-mondial-700w-pe-42-10x/p/MLB24510866?pdp_filters=item_id%3AMLB3399058127&sid=bookmarks#polycard_client=wishlist&wid=MLB3399058127&sid=bookmarks" },
  { id: "kit-potes-hermeticos", nome: "Kit 10 Potes Herméticos Empilháveis Rebirth", preco: 78.90, categoria: "utensilios", unique: true, destaque: false, img: "kit-potes-hermeticos.webp", link: "https://www.mercadolivre.com.br/kit-10-pote-hermeticos-empilhaveis-porta-mantimento-rebirth/p/MLB67631120?pdp_filters=item_id%3AMLB4850874397&sid=bookmarks#polycard_client=wishlist&wid=MLB4850874397&sid=bookmarks" },
  { id: "mixer-elgin", nome: "Mixer Master Mix 5 em 1 Elgin 1000W", preco: 308.34, categoria: "cozinha", unique: true, destaque: false, img: "mixer-elgin.webp", link: "https://www.mercadolivre.com.br/mixer-master-mix-5-em-1-elgin-1000w-110v-5-funcoes-prateado/p/MLB67473207?pdp_filters=item_id%3AMLB6610790608&sid=bookmarks#polycard_client=wishlist&wid=MLB6610790608&sid=bookmarks" },
  { id: "aspirador-po", nome: "Aspirador de Pó Vertical Electrolux 1100W 2 em 1", preco: 154.00, categoria: "lavanderia", unique: true, destaque: false, img: "aspirador-po.webp", link: "https://www.mercadolivre.com.br/aspirador-de-po-vertical-electrolux-1100w-cabo-de-5m-portatil-de-mao-2-em-1-potente-com-capacidade-12l-filtro-hepa-preto/p/MLB18781058?pdp_filters=item_id%3AMLB3633925158&sid=bookmarks#polycard_client=wishlist&wid=MLB3633925158&sid=bookmarks" },
  { id: "cafeteira-eletrica", nome: "Cafeteira Elétrica Electrolux Experience Programável", preco: 297.69, categoria: "cozinha", unique: true, destaque: false, img: "cafeteira-eletrica.webp", link: "https://www.mercadolivre.com.br/cafeteira-eletrica-electrolux-ecm25-experience-programavel-com-timer-preto-e-inox/p/MLB19434520?pdp_filters=item_id%3AMLB4976836220&sid=bookmarks#polycard_client=wishlist&wid=MLB4976836220&sid=bookmarks" },

  { id: "jogo-de-cama", nome: "Jogo de Cama 600 Fios 100% Algodão Queen 3 Peças", preco: 67.06, categoria: "quarto", unique: false, destaque: false, img: "jogo-de-cama.webp", link: "https://produto.mercadolivre.com.br/MLB-5449040108-jogo-de-cama-600-fios-100-algodo-queen-3-pecas-_JM?searchVariation=188531796651&attributes=COLOR_SECONDARY_COLOR%3AQXp1bCBqZWFucw%3D%3D&sid=bookmarks#polycard_client=wishlist&sid=bookmarks" },
  { id: "coberdrom", nome: "Coberdrom Queen Cobertor Casal Dupla Face Sherpa", preco: 168.00, categoria: "quarto", unique: false, destaque: false, img: "coberdrom.webp", link: "https://www.mercadolivre.com.br/coberdrom-queen-220-x-240-cobertor-casal-dupla-face-pele-carneiro-sherpa-quente-soft-luxo-inverno-acochoado-grosso-insonia-edredom-sofisticado-grande-pesado-490g-m2-cor-cinza/p/MLB67646615?pdp_filters=item_id%3AMLB4665612193&sid=bookmarks#polycard_client=wishlist&wid=MLB4665612193&sid=bookmarks" },
  { id: "cobertor-queen-kit2", nome: "Cobertor Queen Manta Microfibra Kit com 2", preco: 84.00, categoria: "quarto", unique: false, destaque: false, img: "cobertor-queen-kit2.webp", link: "https://www.mercadolivre.com.br/cobertor-queen-manta-microfibra-fleece-kit-com-2/p/MLB69615425?pdp_filters=item_id%3AMLB4676263471&sid=bookmarks#polycard_client=wishlist&wid=MLB4676263471&sid=bookmarks" },
  { id: "edredom-queen", nome: "Edredom Queen Dupla Face Extra Soft Cinza", preco: 209.00, categoria: "quarto", unique: false, destaque: false, img: "edredom-queen.webp", link: "https://www.mercadolivre.com.br/edredom-queen-dupla-face-extra-soft-micro-percal-bf-colchoes-cinza-lisa/p/MLB66908409?pdp_filters=item_id%3AMLB6777089348&sid=bookmarks#polycard_client=wishlist&wid=MLB6777089348&sid=bookmarks" },
  { id: "kit-potes-vidro", nome: "Kit 10 Potes de Vidro Herméticos Star House", preco: 64.70, categoria: "utensilios", unique: false, destaque: false, img: "kit-potes-vidro.webp", link: "https://www.mercadolivre.com.br/kit-10-potes-vidro-370ml-hermetico-marmita-forno-refratario-star-house/p/MLB53222545?pdp_filters=item_id%3AMLB4220924519&sid=bookmarks#polycard_client=wishlist&wid=MLB4220924519&sid=bookmarks" },
  { id: "toalhas-karsten", nome: "Jogo de Toalhas Karsten Banhão e Rosto 4 Peças", preco: 189.00, categoria: "banheiro", unique: false, destaque: false, img: "toalhas-karsten.webp", link: "https://www.mercadolivre.com.br/jogo-de-toalhas-karsten-banhao-e-rosto-4-pecas/p/MLB61736929?pdp_filters=item_id%3AMLB5946981776&sid=bookmarks#polycard_client=wishlist&wid=MLB5946981776&sid=bookmarks" },
  { id: "kit3-toalhas-banho", nome: "Kit 3 Toalhas de Banho Gigante Luxo 70x1,40", preco: 62.56, categoria: "banheiro", unique: false, destaque: false, img: "kit3-toalhas-banho.webp", link: "https://www.mercadolivre.com.br/kit-3-toalhas-de-banho-gigante-luxo-70x140-grossa-atacado/up/MLBU3856659729?pdp_filters=item_id%3AMLB6507584804&sid=bookmarks#polycard_client=wishlist&wid=MLB6507584804&sid=bookmarks" },
  { id: "toalhas-super-luxo", nome: "Jogo de Toalhas de Banho Super Luxo 4 Peças", preco: 107.91, categoria: "banheiro", unique: false, destaque: false, img: "toalhas-super-luxo.webp", link: "https://www.mercadolivre.com.br/jogo-toalhas-de-banho-c-4-pcs-super-luxo-gigante-grossa-banco-e-fendi/p/MLB68671858?pdp_filters=item_id%3AMLB6677084348&sid=bookmarks#polycard_client=wishlist&wid=MLB6677084348&sid=bookmarks" },
  { id: "toalhas-buddemeyer", nome: "Jogo de Toalhas Buddemeyer Brisa 4 Peças", preco: 142.40, categoria: "banheiro", unique: false, destaque: false, img: "toalhas-buddemeyer.webp", link: "https://www.mercadolivre.com.br/jogo-de-toalhas-buddemeyer-brisa-banho-begemarrom-4-pecas/p/MLB53715102?pdp_filters=item_id%3AMLB5973935708&sid=bookmarks#polycard_client=wishlist&wid=MLB5973935708&sid=bookmarks" },
];
